name: Build Docker images

on:
  # Allow manual runs.
  workflow_dispatch:
  # Also run on updates to this repo.
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
  # Run on PRs except for documentation.
  pull_request:
    paths-ignore:
      - '**/*.md'
  
env:
  # Only push the image on merges to main
  PUSH_IMAGE: ${{ github.ref == 'refs/heads/master' }}

jobs:

  build-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set datestamp for image tagging
        run: |
          echo DATESTAMP=$(date +%Y.%m.%d) >> $GITHUB_ENV

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        if: ${{ env.PUSH_IMAGE == 'true' }}
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        if: ${{ env.PUSH_IMAGE == 'true' }}
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push `starbound-server` Docker image
        uses: docker/build-push-action@v2
        with:
          tags: |
            didstopia/starbound-server:latest
            didstopia/starbound-server:v${{ env.DATESTAMP }}
            ghcr.io/didstopia/starbound-server:latest
            ghcr.io/didstopia/starbound-server:v${{ env.DATESTAMP }}
          platforms: linux/amd64
          push: ${{ env.PUSH_IMAGE }}
